::ii;;:::::,:,,,,,,,,,,,....````.........``````..,:;iiiiiiiii;;;;;;;;;;;::::,,,.,:;;;;:::::::::,
::i;;;:::::::,,,,,,,,,,,,...````.......,;*##znnnnzz#+*iiiii;;;;;;;;;;;;::::,,,,.,:;;;;;:::::::,,
::i;;::::::::,,,,,,,:,,,,....```...,;#xWWWWWWWWWWMMMMMxn#*i;;;;;;;;;;;;::::,,,,,,:;;;;;:::::::,,
::;;;::::::,:,,,,,,,:,,,,....````,+xWWWWWWW@WWWWWWWWMMMMMxn#*;;;;;;;;;:::::,,,,,:;;;;;;;::::::,,
::;;;::::::::,,,,,,,,,,,,,....`,#MWWWWWWWWW@@WWWWWWWWWWMMMMMxz*;:;;;;::::::,,,,::;;;;;;::::::,,;
::;;::::::::::,,,,,,,,,,,,....+MWW@@@@@WWWWWWWWWWWWMWWWMMMMMxxxn*;:::::::::,,,,:;;;;;;;;;::::,,n
::;;::::::::::,,,,,,,,,,,,..:nW@@@@@@@@WWWWWWWWWWWWMMMMMMMMMMMxxnz*::::::::,,,::;;;;;:;:::::,,iW
::;::::::::::::,,,,,,,,,,,.*MW@@@@@@@@@@@@WWWWWWWWWWWMMMMMMMMxxxxnn#;::::::,,,::;;;;;;;:::::,,nW
::;::::::::::,,,,,,,:,,,,,#W@@@@@@@@@@@@@W@WWWWWWWWWMMMMMMMxxxxxxnnnz*:::::,,::;;;;;;;::::::,;WW
::::::::::::::,,,,,,:::,,zWWW@@@@@@@@@@@@@WWWWWWWMMMMMMMMMxxxxxxnnnnzz*:::::::;;;;;;;:::::::,zWW
:::::::::::::,:,,,,,:::,#WW@@@@@@@@@@@@@@WWWWWWMMMMMMMMMxxxxxxxxnnnnz#z+:::::;;;;;;;;::::::,;WWW
::::::::::::,,,,,,,:::,+WWW@@@@@@@@@@@@@@WWWWWMMMMMMMMMMxMxxxxxxnnnzzzz##:::;;;i;;;;:::::::,#WWW
::::::::::::,,,,,,::::*WW@@@@@@@@@@@@@WWWWWWWWMMMMMMMMMMMxxxxxxnnnzz#zz##+:;;;;;;;;:::::::::xWWW
:::,,:::::::,,,,,::::;xWW@@@@@@@@@WW@WWWWWWWWWMMMMMMMMMMxxxxxnnnnz########+;;;;;;;;::::::::iMWWW
::,,,,::::::,,,,:::::zWWW@@@@@@WWMMWWWWWMWWMMMMMMMMMMMMxxxxxxnnnzz#++*+++##+;;;;;;::::::::,+WWWW
::,,,,:::::,,,,:::::iMWW@@@@@WMzi,.:+MMMMMMMMMMMMMMMMMMMMxxxxnnnzz#+****++##*;;;;::::::::::zMWWW
::,,,,::::,,,,::::::nWW@@@@@WMi``````;MMMMMxxxMMMMMMMMMMMxxxxxnnnz++***ii*+##;;;;::::::::,:xWWWM
::,,,,:::::,:::::::*MWW@@@@WM;``:+zi``zMMMMxxxxxxxxxMMMMxxxxxxnnnz#+**iii;*#z*:;:::::::::,;MWWWM
::.,,,:::::::::::::nMWW@@@WW#``+@@@@+`iMMMxxxxxxxxxxxxxMxxxxxnnnzz##+*i;;;i+#z;::::::::::,iWWWMM
::..,,::::::::::::iMWWW@@@WM,`*@@@@@M`;MMMxxxxxxxxxxxxxxxxxxxxnnzzzzz#*iiii*+z+::::::::::,*WWWMM
::...,::::::::::::zMWWWW@@Wn`.M#@#@@M`iMMxxxxxxxxxxxxxxxxxxxxxxnzzzzzzz#****+#z:::::::::,,+WWWMM
::...,:::::::::::;xMWWW@@@W#`:@#@##@n`#MMxxnnnnnnnnnxxxxxxxxxxxnzz#+ii+z#+***#zi:::::::,,,#WWWMM
::``.,:::::::::::*MMWWWW@@W#`:@#@#@W;,xMxxxnnnnnnnnnnxxxxxxxxxxxzn*.```iz+**++z+::::::,,,,#WWWWW
::``.,,::::::::::zMMWWWWWWWn..x#@@W;.#xMxxxnnnzznznnnxxxxxxxxxxxxz``   `*z+++#zz::::::,,,,#W@WWM
::```.,::::::::::nMMWWWWW@WM;`,+z+,.+xMMxxnnnnnnnnnnnnxxxxxxxxxxxi`.;:` `##+++#zi:::,,,,,,+W@WWW
::```.,:::::::::ixMMMWWWW@WWx:.``.;nMxMxxnnnxnnnnnnnnnxxxxxMxxxnx:.x@@#``:n####z*:::,,,,,,iW@@WW
::```..,::::::::*xMMMWWWW@WWWWxnnMMxxMxxxxMMMxxxnxxxxxxxxxxMMMxxx,+###@+ .zz##zn#:::,,,,,,:M@@WW
::```..,::::::::+xMMMWWWWWWWWWWWWMMMMMxxMxxnnzzzzzzznnxxxxMMMMxxx:z####M.`+nzznnz:,,,,,,,.,x@@@W
::```..,::;:::::#xMMMWWWWW@WWWWWMMMMMMxxnzzz#####+++++#zxxxMMMMxMiz@###@: +nzznzz:,,,,,,,.,+W@@W
::````.,,::;::::#xMMMWWWW@@WWWWWMMMMMMxnzzz######++++++*+#xMMMMxW#i@###@: +nnnnzz:,,,,,,,.,;MW@W
::````..,,::::::#xMMMMWWWW@WWWWWWMMMMxzzzzz#######++++***i*nMMMMWM:x@@#W.`znnnnnn;,,,,,,....#W@@
::`````..,,:::::#xxMMMWWW@@@WWWWWMMMxnzzzzzz#####++++*****i;zMMxWWz,n@Wi`,nxxnnnzi,,,,,.....:MW@
::``````...,,,:,+xxMMMWWWW@@WWWWWMMMnzzzzzzz######+++****iii;nMxMWW*.,.``+nnxxnnni,,,,,,.....+MW
::````````...,.,+xxMMMWWWWWWWWWWWMMxzzzzzzz########++***iii;;+MMMMMM#:.,+nnxxxnnni,,,.,,.....,zW
::.`````````....ixxxMMWWWWWWWWWWWMMnzzzzzz##########++*i;:;:;inMMxxMMMxxxnxxxxnnni,,,,,.......:x
::..``````````.`:nxMMMMWWWWWWWWWWWMzzzzz#z########++++*i;,,,;i#MMMxxMxxxxxxxxxnnn;,,,,..,......i
::...````   ````.zxxMMMMWWWWWWWWWWMzzzzz######++++++++**i:.,;i*MMMMMMxxMMxxxxxnnn:,,,,,.........
::,..````    ````+nxxMMMMWWWWWWWWWMzzzz######++++**++++**i;;ii*xMMMMMMMMMMxxxxxnn:,,,,,.........
::,,..```      ``:nxxMMMMMWWWWWWWWWzzzzzz#######+++####+++*****xMMMMMMMMMMxxxxxxn,,,,,,,........
::,,..``       ``.zxxMMMMMWWWWWWWWWxzzzzzzzz##############+++*+xMMMMMMMMMMxxxxxn#,,,,,..........
:::,..``       ```inxxMMMMWWWWWWWWWWxzzzzzzzzzzz###########++++MMMWMMMMMMMxxxxxx+,,,,,..........
:::,..``      ```.,#nxxMMMWWWWWWWWW@WMnnzzzzzzzzzz####zzz###++#MMWWMMMMMMMxxxxxni,,,............
:::,..``      ``...:zxxMMMMWWWWWWWWW@@Wxnnnzzzzzzzzzzzzzz###+#xWWWWMMMMMMMxxxxxz:,,,,...........
::,,.```    ````..,,:#xxMMMWWWWWWWWW@@@@WMxnnnzzzzzzzzzzzz###zWWWWWWMMMMMMxxxxx#,,,,............
::,..```   ` ```.,,,,,+nxMMWWWWWWWWW@@@@@@@WMxnnnznzzzzzz###nWWWWWWMMMMMMxxxxxxi,,,.............
::,..``    ````..,,,,,,;zxMW@@@@@W@@@@@@@@@@@@@WWMxnnzzzzznMWWWWWWWMMMMMMMxxxxz,,.,.............
::,..```   ````..,,,,,,,,*xW@@@@@@@@@@@@@@@@@@@@@@@@WWWWWWW@@WWWWWWMMMMMMMxxxxi,,,,,............
::,.``````````..,,,,,,,,,.:#W@@@@#@@@@@@@@@@@@@@@@@@@@@@@WWWWWWWWWWMMMMMMMxxx+,,,,.,............
::,.``````````.,,:,,,,,,,,,.:M#######@@@@@@@@@@@@@@@@@@WWWWWWWWWWMMMMMMMMMMxz,,,,,..............
::..`````````..,,:,,,,,,,,,,+@###########@@@@@@@@@@@@@WWWWWWWWWWWMMMMMMMMMxn:,,,,,,.............
::..`````````.,,::,,,,,.,.iM#############@@@#@@@@@@@WW@WWWWWWWWMMMMMMMMMMMz,.,,,,,..............
::..````````..,:::,,,,,.:z@####################@@@@WWWWWWWWMMMMMMMMMMMMMx+,,,,,,,,..............
::..````````.,,:::,,,.,+M@@@######################@@@WWWMMMMMxxxxxxxMMMn:,,,,,,,....,...........
::..```````..,:::,,,,;x@@@@@@@#@@###################@@@@@WWWWMMMMMMWMxnn#;,.,,,,,,..............
::..```````..,:::,,,zW@@@@@@@@@@@##################################Wnnzznn+:..,.,,,,............
::..``````..,::::,ix@@@@@@@@@@@@@@@###############################Wnz#zzzzzz+:.,.,,...,.........
::..``````..,::::+W@@@@@@@@@@@@@@@@@##########################@##Wnzzzzzzz##zz;.,....,,.........
::..``````.,,::;n@@@@@@@@@@@@@@@@@@@@#@@@#####################@@Wxxnzzzzz##znz#;.....,..........
::..`````..,::iM@@@@@@@@@@@@@@@@W@@@@@@#@######################Wnnnnnz#####nnn#+;..,..,.........
::..`````.,,:*W@@@@@@@@@@@@@@@@WW@@@@@@@@@@@@@@@#############@x#++#znnz####nnnz##;.,,...........
::..````..,,+W@@@@@@@@@@@@@@@@WWWW@@@@@@@@@@@@@@@@@@@@#####@Wz*i;ii*+zxxzzznnnzz##i.,,..........
::...```..,*W@@@@@@@@@@@@@@@@WWWWWW@W@@WWWW@@@@@@@@@####@@@Mn#+++++***+xMxnnnnnz###*.,........,z
::...``..,*W@@@@@@@@@@@@@@@@@WWWWWWWWWWWWWW@@@@@@@@@##@@@WMxxxxxxxxxxn#+zWWxxxnnz##z+:.....,:+W@
::...``..iM@@@@@@@@@@@@@@@@@@WWWWWWWWWWWWWWW@@W@@@@@@@@WMMxxxnzznnxxxxxnzzWWxxnnzz#znxz**+zMW@@@
::...```;MW@@@@@@@@@@W@WWWWWWWWWWWWWWWWWWWWW@W@@@@@@@WMMxn+;,..`..,;#xMxxnzWMMxnnzzzznW@@@@@@@@@
::..```:MW@@@@@W@@@W@W@@WWWWWWWWMMMMWWWWWWWWW@@@WWWWMMMzi,..`````````,+nMxxzWWMxnnnnzzxW@@@@@@@W
::.```:xWW@@@@@@@@@W@@@WWWWWWWWMMMMMMMWWWWWW@@WWWWMxxn*:,,...```` ````.:+xMxnWWMxxnnnznxW@@@@@WW
::```.nWWW@@@@@@@@W@W@WWWWWWWWMMMMWMMMMWWWWW@WMMWMxx#:::,..````     ````.;nMxx@WMMxxxnnxMW@WWWWW
::```zWW@@@@@@@WW@WW@@WWWWWWMMMMMMMMMMWWWWW@WMMMMMxi::,,..`````       ```.:zMxx@WWMxxxnnxMWWWWWW
::``*WWWW@@@@WWWWWWWWWWWWWWWMMMMMMMMWWWWWW@WMxMMxn;::,,....````         ```,zMxM@WMMMMxxxMMWWWWW
::`:MWW@@@@@@WW@WWWWWWWWWWWWMMMMMMMMWWWWW@WMxxMxz;::,,,,,..```            ``,nMxW@WMWMMMMMMWWWWW
::.nWW@@@@@@@@WWWWWWWWWWWWWMxMMMMMMWWWWW@WMxxxxz;::,,,,,..``               ``,xMx@@WWWWMWWWWWWWW

@echo off
:: 'ping' a port / just check if it returns a value
set input=%1
shift

::
curl -s %input%
